
import type { Book } from './types';

export const booksData: Book[] = [
    // شریعتی
    { id: 1, title: 'هبوط', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1381', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 2, title: 'کویر', author: 'علی شریعتی', originalPubDate: '۱۳۴۸', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 3, title: 'اسلام‌شناسی (درس‌های ارشاد)', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 4, title: 'فاطمه، فاطمه است', author: 'علی شریعتی', originalPubDate: '۱۳۴۸', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 7, title: 'انسان بی‌خود', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1388', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 8, title: 'مذهب علیه مذهب', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1385', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 9, title: 'زن در چشم و دل محمد', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1382', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 10, title: 'نیایش', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1383', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 11, title: 'چه باید کرد؟', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1379', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 12, title: 'شهادت', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1379', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 13, title: 'آری، اینچنین بود برادر', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 14, title: 'حسین وارث آدم', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 15, title: 'پدر، مادر، ما متهمیم', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1381', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 16, title: 'علی حقیقتی بر گونه اساطیر', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1380', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 17, title: 'نوروز', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1385', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 18, title: 'حج', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1383', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 19, title: 'تاریخ ادیان', author: 'علی شریعتی', originalPubDate: 'دهه ۵۰', readYear: '1378', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 20, title: 'هیپیاس بزرگ', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1404/06/20', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 21, title: 'هیپیاس کوچک', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1404/06/20', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 22, title: 'آپولوژی', author: 'افلاطون', originalPubDate: '۳۹۹ ق.م', readYear: '1382', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: '22.1', title: 'آپولوژی', author: 'افلاطون', originalPubDate: '۳۹۹ ق.م', readYear: '1392', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: '22.2', title: 'آپولوژی', author: 'افلاطون', originalPubDate: '۳۹۹ ق.م', readYear: '1397', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 23, title: 'ضیافت', author: 'افلاطون', originalPubDate: '۳۸۵ ق.م', readYear: '1380', genre: 'فلسفه', translator: 'محمدعلی فروغی', nationality: 'یونان' },
    { id: '23.1', title: 'ضیافت', author: 'افلاطون', originalPubDate: '۳۸۵ ق.م', readYear: '1381', genre: 'فلسفه', translator: 'محمدعلی فروغی', nationality: 'یونان' },
    { id: '23.2', title: 'ضیافت', author: 'افلاطون', originalPubDate: '۳۸۵ ق.م', readYear: '1385', genre: 'فلسفه', translator: 'محمدعلی فروغی', nationality: 'یونان' },
    { id: 24, title: 'کریتون', author: 'افلاطون', originalPubDate: '۳۹۹ ق.م', readYear: '1383', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 25, title: 'گرگیاس', author: 'افلاطون', originalPubDate: '۳۸۰ ق.m', readYear: '1384', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 26, title: 'خارمیدس', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1384', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 81, title: 'پروتاگراس', author: 'افلاطون', originalPubDate: '۳۸۰ ق.م', readYear: '1399', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 82, title: 'پروتاگراس', author: 'افلاطون', originalPubDate: '۳۸۰ ق.م', readYear: '1404/08/10', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 105, title: 'لوسیس', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1383', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: '105.1', title: 'لوسیس', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1404/08/10', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 109, title: 'لاخس', author: 'افلاطون', originalPubDate: 'قرن ۴ ق.م', readYear: '1404/08/11', genre: 'فلسفه', translator: 'محمدحسن لطفی', nationality: 'یونان' },
    { id: 27, title: 'دیوار', author: 'ژان پل سارتر', originalPubDate: '۱۳۱۸', readYear: '1404/08/08', genre: 'رمان فلسفی', translator: 'صادق هدایت', nationality: 'فرانسه' },
    { id: 28, title: 'برزخ', author: 'ژان پل سارتر', originalPubDate: '۱۳۲۳', readYear: '1402', genre: 'فلسفه', translator: 'حمید سمندریان', nationality: 'فرانسه' },
    { id: 29, title: 'شیطان و خدا', author: 'ژان پل سارتر', originalPubDate: '۱۳۳۰', readYear: '1384', genre: 'فلسفه', translator: 'امید شادکامی', nationality: 'فرانسه' },
    { id: 30, title: 'تهوع', author: 'ژان پل سارتر', originalPubDate: '۱۳۱۷', readYear: '1383', genre: 'رمان فلسفی', translator: 'امیرجلال‌الدین اعلم', nationality: 'فرانسه' },
    { id: 31, title: 'دست‌های آلوده', author: 'ژان پل سارتر', originalPubDate: '۱۳۲۷', readYear: '1385', genre: 'فلسفه', translator: 'جلال آل احمد', nationality: 'فرانسه' },
    { id: 32, title: 'مگس‌ها', author: 'ژان پل سارتر', originalPubDate: '۱۳۲۲', readYear: '1384', genre: 'فلسفه', translator: 'صادق هدایت', nationality: 'فرانسه' },
    { id: 33, title: 'اگزیستانسیالیسم و اصالت بشر', author: 'ژان پل سارتر', originalPubDate: '۱۳۲۵', readYear: '1381', genre: 'فلسفه', translator: 'مصطفی رحیمی', nationality: 'فرانسه' },
    { id: 83, title: 'در دفاع از روشنفکران', author: 'ژان پل سارتر', originalPubDate: '۱۳۴۴', readYear: '1384', genre: 'فلسفه', translator: 'رضا سیدحسینی', nationality: 'فرانسه' },
    { id: 34, title: 'بیگانه', author: 'آلبر کامو', originalPubDate: '۱۳۲۱', readYear: '1404/08/08', genre: 'رمان فلسفی', translator: 'جلال آل احمد', nationality: 'فرانسه' },
    { id: 35, title: 'سقوط', author: 'آلبر کامو', originalPubDate: '۱۳۳۵', readYear: '1404/08/09', genre: 'رمان فلسفی', translator: 'پرویز شهدی', nationality: 'فرانسه' },
    { id: 36, title: 'جامعه‌شناسی خودکامگی', author: 'علی رضاقلی', originalPubDate: '۱۳۶۳', readYear: '1404/08/07', genre: 'جامعه شناسی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 37, title: 'جامعه‌شناسی خودکامگی', author: 'علی رضاقلی', originalPubDate: '۱۳۶۳', readYear: '1404/04/08', genre: 'جامعه شناسی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 38, title: 'جامعه‌شناسی نخبه‌کشی', author: 'علی رضاقلی', originalPubDate: '۱۳۷۷', readYear: '1404/07/26', genre: 'جامعه شناسی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 39, title: 'عرفان و منطق', author: 'برتراند راسل', originalPubDate: '۱۲۹۷', readYear: '1383', genre: 'فلسفه', translator: 'نجف دریابندری', nationality: 'انگلیس' },
    { id: 40, title: 'زندگینامه برتراند راسل', author: 'برتراند راسل', originalPubDate: '۱۳۴۶', readYear: '1382', genre: 'فلسفه', translator: 'نجف دریابندری', nationality: 'انگلیس' },
    { id: 41, title: 'چرا مسیحی نیستم', author: 'برتراند راسل', originalPubDate: '۱۳۳۶', readYear: '1400', genre: 'فلسفه', translator: 'نجف دریابندری', nationality: 'انگلیس' },
    { id: 42, title: 'بوف کور', author: 'صادق هدایت', originalPubDate: '۱۳۱۵', readYear: '1380', genre: 'رمان فلسفی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 43, title: 'منطق‌الطیر', author: 'عطار نیشابوری', originalPubDate: 'قرن ۶', readYear: '1381', genre: 'عرفان', translator: 'تصحیح شفیعی کدکنی', nationality: 'ایران' },
    { id: 44, title: 'دیوان حافظ', author: 'حافظ شیرازی', originalPubDate: 'قرن ۸', readYear: '1382', genre: 'شعر', translator: 'تصحیح قزوینی', nationality: 'ایران' },
    { id: 45, title: 'مثنوی معنوی', author: 'مولانا', originalPubDate: 'قرن ۷', readYear: '1383', genre: 'شعر', translator: 'تصحیح نیکلسون', nationality: 'ایران' },
    { id: 46, title: 'فیه ما فیه', author: 'مولانا', originalPubDate: 'قرن ۷', readYear: '1382', genre: 'عرفان', translator: 'تصحیح فروزانفر', nationality: 'ایران' },
    { id: 110, title: 'کلیات شمس', author: 'مولانا', originalPubDate: 'قرن ۷', readYear: '1382', genre: 'شعر', translator: 'تصحیح فروزانفر', nationality: 'ایران' },
    { id: 47, title: 'خط سوم', author: 'ناصرالدین صاحب‌الزمانی', originalPubDate: '۱۳۵۱', readYear: '1382', genre: 'عرفان', translator: 'تألیفی', nationality: 'ایران' },
    { id: '47.1', title: 'خط سوم', author: 'ناصرالدین صاحب‌الزمانی', originalPubDate: '۱۳۵۱', readYear: '1380', genre: 'عرفان', translator: 'تألیفی', nationality: 'ایران' },
    { id: 48, title: 'اسفار اربعه', author: 'ملاصدرا', originalPubDate: 'قرن ۱۱', readYear: '1384', genre: 'فلسفه', translator: 'محمد خواجوی', nationality: 'ایران' },
    { id: 49, title: 'اخبار حلاج', author: 'لوئی ماسینیون', originalPubDate: '۱۳۰۱', readYear: '1384', genre: 'عرفان', translator: 'حمید حمید', nationality: 'فرانسه' },
    { id: 50, title: 'مصائب حلاج', author: 'لوئی ماسینیون', originalPubDate: '۱۳۰۱', readYear: '1388', genre: 'عرفان', translator: 'ضیاءالدین دهشیری', nationality: 'فرانسه' },
    { id: 51, title: 'سرّ نی', author: 'عبدالحسین زرین‌کوب', originalPubDate: '۱۳۶۴', readYear: '1384', genre: 'عرفان', translator: 'تألیفی', nationality: 'ایران' },
    { id: 52, title: 'پله‌پله تا ملاقات خدا', author: 'عبدالحسین زرین‌کوب', originalPubDate: '۱۳۷۰', readYear: '1384', genre: 'عرفان', translator: 'تألیفی', nationality: 'ایران' },
    { id: 53, title: 'بحر در کوزه', author: 'عبدالحسین زرین‌کوب', originalPubDate: '۱۳۶۶', readYear: '1384', genre: 'عرفان', translator: 'تألیفی', nationality: 'ایران' },
    { id: 54, title: 'مقالات شمس', author: 'شمس تبریزی', originalPubDate: 'قرن ۷', readYear: '1385', genre: 'عرفان', translator: 'تصحیح موحد', nationality: 'ایران' },
    { id: 55, title: 'خمسه (لیلی و مجنون)', author: 'نظامی گنجوی', originalPubDate: 'قرن ۶', readYear: '1380', genre: 'شعر', translator: 'تصحیح وحید دستگردی', nationality: 'ایران' },
    { id: 56, title: 'عقل سرخ', author: 'سهروردی', originalPubDate: 'قرن ۶', readYear: '1383', genre: 'فلسفه', translator: 'تصحیح هانری کربن', nationality: 'ایران' },
    { id: 57, title: 'تفسیر سوره نور', author: 'ملاصدرا', originalPubDate: 'قرن ۱۱', readYear: '1385', genre: 'فلسفه دینی', translator: 'محمد خواجوی', nationality: 'ایران' },
    { id: 58, title: 'گلستان', author: 'سعدی', originalPubDate: '۶۳۷', readYear: '1382', genre: 'شعر', translator: 'تصحیح فروغی', nationality: 'ایران' },
    { id: 59, title: 'بوستان', author: 'سعدی', originalPubDate: '۶۳۶', readYear: '1382', genre: 'شعر', translator: 'تصحیح فروغی', nationality: 'ایران' },
    { id: 60, title: 'مقدمه بر المشاعر', author: 'هانری کربن', originalPubDate: '۱۳۴۳', readYear: '1382', genre: 'فلسفه', translator: 'تألیفی', nationality: 'فرانسه' },
    { id: 61, title: 'قلعه حیوانات', author: 'جورج اورول', originalPubDate: '۱۳۲۴', readYear: '1380', genre: 'رمان فلسفی', translator: 'امیر امیرشاهی', nationality: 'انگلیس' },
    { id: 62, title: '۱۹۸۴', author: 'جورج اورول', originalPubDate: '۱۳۲۸', readYear: '1381', genre: 'رمان فلسفی', translator: 'صالح حسینی', nationality: 'انگلیس' },
    { id: 63, title: 'شازده کوچولو', author: 'آنتوان دو سنت اگزوپری', originalPubDate: '۱۳۲۲', readYear: '1380', genre: 'رمان فلسفی', translator: 'احمد شاملو', nationality: 'فرانسه' },
    { id: 64, title: 'هملت', author: 'ویلیام شکسپیر', originalPubDate: '۱۲۸۰', readYear: '1382', genre: 'نمایشنامه', translator: 'مسعود فرزاد', nationality: 'انگلیس' },
    { id: 65, title: 'مسخ', author: 'فرانتس کافکا', originalPubDate: '۱۲۹۴', readYear: '1383', genre: 'رمان فلسفی', translator: 'صادق هدایت', nationality: 'اتریش' },
    { id: 66, title: 'کمدی الهی', author: 'دانته آلیگیری', originalPubDate: '۱۰۰۱', readYear: '1380', genre: 'فلسفه', translator: 'شجاع‌الدین شفا', nationality: 'ایتالیا' },
    { id: 67, title: 'روی ماه خداوند را ببوس', author: 'مصطفی مستور', originalPubDate: '۱۳۷۹', readYear: '1379', genre: 'رمان فلسفی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 68, title: 'استخوان خوک و دست‌های جذامی', author: 'مصطفی مستور', originalPubDate: '۱۳۸۳', readYear: '1383', genre: 'رمان فلسفی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 69, title: 'من دانای کل هستم', author: 'مصطفی مستور', originalPubDate: '۱۳۸۸', readYear: '1388', genre: 'رمان فلسفی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 70, title: 'خشم فرشتگان', author: 'سیدنی شلدون', originalPubDate: '۱۳۶۱', readYear: '1375', genre: 'رمان', translator: 'احمدreference', nationality: 'آمریکا' },
    { id: 71, title: 'آناکارنینا', author: 'لئو تولستوی', originalPubDate: '۱۲۵۶', readYear: '1383', genre: 'رمان فلسفی', translator: 'سروش حبیبی', nationality: 'روسیه' },
    { id: 72, title: 'مائده‌های زمینی', author: 'آندره ژید', originalPubDate: '۱۲۷۶', readYear: '1380', genre: 'رمان فلسفی', translator: 'جلال آل احمد', nationality: 'فرانسه' },
    { id: 73, title: 'ارغنون', author: 'مهدی اخوان ثالث', originalPubDate: '۱۳۳۰', readYear: '1381', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 74, title: 'زمستان', author: 'مهدی اخوان ثالث', originalPubDate: '۱۳۳۵', readYear: '1382', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 75, title: 'آخر شاهنامه', author: 'مهدی اخوان ثالث', originalPubDate: '۱۳۳۸', readYear: '1383', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 76, title: 'از این اوستا', author: 'مهدی اخوان ثالث', originalPubDate: '۱۳۴۴', readYear: '1383', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 77, title: 'سراب', author: 'هوشنگ ابتهاج (سایه)', originalPubDate: '۱۳۳۰', readYear: '1384', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 78, title: 'سیاه‌مشق', author: 'هوشنگ ابتهاج (سایه)', originalPubDate: '۱۳۳۲', readYear: '1383', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 79, title: 'شبگیر', author: 'هوشنگ ابتهاج (سایه)', originalPubDate: '۱۳۳۲', readYear: '1385', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 80, title: 'زمین', author: 'هوشنگ ابتهاج (سایه)', originalPubDate: '۱۳۳۴', readYear: '1385', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 84, title: 'چند برگ از یلدا', author: 'هوشنگ ابتهاج (سایه)', originalPubDate: '۱۳۴۴', readYear: '1382', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 85, title: 'تئوری موسیقی', author: 'مصطفی کمال پورتراب', originalPubDate: '۱۳۴۵', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 86, title: 'تئوری موسیقی', author: 'علینقی وزیری', originalPubDate: '۱۳۱۳', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 87, title: 'تئوری موسیقی', author: 'پرویز منصوری', originalPubDate: 'دهه ۵۰', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 88, title: 'موسیقی کبیر', author: 'ابونصر فارابی', originalPubDate: 'قرن ۳', readYear: '1386', genre: 'موسیقی', translator: 'آذرتاش آذرنوش', nationality: 'ایران' },
    { id: 89, title: 'دستگاه در موسیقی ایرانی', author: 'هرمز فرهت', originalPubDate: '۱۳۶۸', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 90, title: 'کتاب سال شیدا ۱', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 91, title: 'کتاب سال شیدا ۲', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.1', title: 'کتاب سال شیدا ۳ و ۴', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1385', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.2', title: 'کتاب سال شیدا ۷ و ۶', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1385', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.3', title: 'کتاب سال شیدa ۵', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.4', title: 'کتاب سال شیدا ۸ و ۹', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1387', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.5', title: 'کتاب سال شیدا ۱۰ و ۱۱', author: 'محمدرضا لطفی', originalPubDate: 'دهه ۷۰', readYear: '1387', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '91.6', 'title': 'کتاب سال شیدا ۱ و ۲', 'author': 'محمدرضا لطفی', 'originalPubDate': 'دهه ۷۰', 'readYear': '1385', 'genre': 'موسیقی', 'translator': 'تألیفی', 'nationality': 'ایران' },
    { id: 92, title: 'ارکستراسیون', author: 'کنت کنان', originalPubDate: '۱۳۳۷', readYear: '1386', genre: 'موسیقی', translator: 'هوشنگ کامکار', nationality: 'آمریکا' },
    { id: 93, title: 'هفت دستگاه موسیقی ایرانی', author: 'مجید کیانی', originalPubDate: '۱۳۷۱', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 94, title: 'نگرشی نو به تئوری موسیقی ایرانی', author: 'داریوش طلایی', originalPubDate: '۱۳۷۲', readYear: '1386', genre: 'موسیقی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 95, title: 'سیر حکمت در اروپا', author: 'محمدعلی فروغی', originalPubDate: '۱۳۱۰', readYear: '1381', genre: 'فلسفه', translator: 'تألیفی', nationality: 'ایران' },
    { id: 96, title: 'آخرت و خدا، هدف بعثت انبیاء؟!', author: 'مهدی بازرگان', originalPubDate: '۱۳۴۱', readYear: '1385', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 97, title: 'گاو (عزاداران بیل)', author: 'غلامحسین ساعدی', originalPubDate: '۱۳۴۳', readYear: '1377', genre: 'رمان', translator: 'تألیفی', nationality: 'ایران' },
    { id: 107, title: 'کباب غاز', author: 'محمدعلی جمال‌زاده', originalPubDate: '۱۳۰۰', readYear: '1375', genre: 'داستان کوتاه', translator: 'تألیفی', nationality: 'ایران' },
    { id: 98, title: 'رباعیات خیام', author: 'عمر خیام', originalPubDate: 'قرن ۵', readYear: '1385', genre: 'شعر', translator: 'تصحیح فروغی', nationality: 'ایران' },
    { id: 99, title: 'قمار عاشقانه', author: 'عبدالکریم سروش', originalPubDate: '۱۳۷۵', readYear: '1383', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: 100, title: 'سفر به دیگر سو', author: 'کارلوس کاستاندا', originalPubDate: '۱۳۵۰', readYear: '1381', genre: 'عرفان', translator: 'مهران کندری', nationality: 'پرو' },
    { id: 101, title: 'بتهوون', author: 'رومن رولان', originalPubDate: '۱۲۸۲', readYear: '1382', genre: 'زندگی‌نامه', translator: 'محمد مجلسی', nationality: 'فرانسه' },
    { id: 102, title: 'قرآن', author: 'محمد', originalPubDate: 'قرن ۱', readYear: '1385', genre: 'فلسفه دینی', translator: 'الهی قمشه‌ای', nationality: 'عربستان' },
    { id: 103, title: 'دوبیتی‌ها (خیام)', author: 'عمر خیام', originalPubDate: 'قرن ۵', readYear: '1387', genre: 'شعر', translator: 'تصحیح فروغی', nationality: 'ایران' },
    { id: '104.1', title: 'ایمان و آزادی', author: 'مجتهد شبستری', originalPubDate: '۱۳۷۶', readYear: '1389', genre: 'فلسفه دینی', translator: 'تألیفی', nationality: 'ایران' },
    { id: '105.2', title: 'ضحاک ماردوش', author: 'علی اکبر سعیدی سیرجانی', translator: 'تألیفی', originalPubDate: '1354', readYear: '1404/08/12', genre: 'جامعه شناسی', nationality: 'ایران' },
    { id: 111, title: 'دوبیتی‌های باباطاهر', author: 'باباطاهر', originalPubDate: 'قرن ۵', readYear: '1376', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 112, title: 'دیوان پروین اعتصامی', author: 'پروین اعتصامی', originalPubDate: '۱۳۱۴', readYear: '1381', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' },
    { id: 113, title: 'دیوان اشعار وحشی بافقی', author: 'وحشی بافقی', originalPubDate: 'قرن ۱۰', readYear: '1380', genre: 'شعر', translator: 'تألیفی', nationality: 'ایران' }
];

export const JALALI_MONTHS = ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'];